apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teleport-relay.fullname" . }}
  labels:
    {{- include "teleport-relay.labels" . | nindent 4 }}
data:
  teleport.yaml: |2
    version: v3
    teleport:
      log:
        severity: DEBUG
        format:
          output: json
      proxy_server: {{ .Values.proxyAddr | quote }}
      {{- with .Values.joinParams }}
      join_params:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    auth_service:
      enabled: false
    proxy_service:
      enabled: false
    ssh_service:
      enabled: false
    relay_service:
      enabled: true
      relay_group: {{ .Values.relayGroup | quote }}
      target_connection_count: {{ .Values.targetConnectionCount }}
      shutdown_delay: {{ .Values.shutdownDelay | quote }}
      {{- with .Values.apiPublicHostnames }}
      api_public_hostnames:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      api_listen_addr: 0.0.0.0:3040
      tunnel_listen_addr: 0.0.0.0:3042
      tunnel_public_addr: {{ .Values.tunnelPublicAddr | quote }}
